# Aneesh Ratnala
# notes: GenAI usage is detailed for the respective helper functions; also, AI was especially helpful with debugging--much of the debug
# statements throughout the code were also generated by Gemini.

import numpy as np
from pid import PID
from scipy.spatial.transform import Rotation as R
import robosuite.utils.transform_utils as T

class StackPolicy(object):
    """
    Policy for the Block Stacking task.

    **Full run** (``segmented=False``): phases 0→1→2→3 in one go (hover A, grasp A,
    hover above B, place on B).

    **Segmented** (``segmented=True``): voice-gated — **grab** runs 0→1, then hold (phase 10);
    **hover** continues 2, then hold (phase 11); **place** runs phase 3 only. Uses the same
    targets as the full run for each segment (no separate place-down motion until phase 3).
    """
    def __init__(self, obs, segmented=False):
        """
        Args:
            obs (dict): Includes 'cubeA_pos' and 'cubeB_pos'.
            segmented: If True, pause after grasp and after B-hover until ``begin_hover`` /
                ``begin_place`` are called (for grab → hover → place voice flow).
        """
        self.cubeA_pos = obs["cubeA_pos"]
        self.cubeB_pos = obs["cubeB_pos"]
        self.segmented = bool(segmented)
        # 0–3: same as full stack; 10 = hold after grasp; 11 = hold above B before place
        self.phase = 0
        self._post_grasp_hold = None
        self._hover_hold_target = None

        eef_pos = obs["robot0_eef_pos"]
        self.controller = PID(kp=10.0, ki=0.1, kd=5.0, target=eef_pos[:3])
        self.dt = 0.05

    def begin_hover(self) -> None:
        """After voice **hover**: leave post-grasp hold and run existing phase-2 motion to above B."""
        if self.phase == 10:
            self.phase = 2

    def begin_place(self) -> None:
        """After voice **place**: leave B-hover hold and run existing phase-3 place-down + release."""
        if self.phase == 11:
            self.phase = 3

    def segment_grab_done(self, obs) -> bool:
        """Segmented: grasp complete and stable at post-grasp hold (phase 10)."""
        if not self.segmented or self.phase != 10 or self._post_grasp_hold is None:
            return False
        eef = obs["robot0_eef_pos"]
        return np.linalg.norm(eef[:3] - self._post_grasp_hold) < 0.03

    def segment_hover_done(self, obs) -> bool:
        """Segmented: reached hold above B (phase 11), before place."""
        if not self.segmented or self.phase != 11 or self._hover_hold_target is None:
            return False
        eef = obs["robot0_eef_pos"]
        return np.linalg.norm(eef[:3] - self._hover_hold_target) < 0.03

    def get_action(self, obs):
        """
        Returns:
            np.ndarray: 7D action (Delta-X, Delta-Y, Delta-Z, Axis-Angle [3], Gripper).
        """
        # initialize 7D action array: [Delta-X, Delta-Y, Delta-Z, Axis-Angle [3], Gripper]
        action = np.zeros(7)
        
        # get current positions
        eef_pos = obs["robot0_eef_pos"]
        cubeA_pos = obs["cubeA_pos"]
        cubeB_pos = obs["cubeB_pos"]
        
        # phase 0: hover over cube A (10cm above)
        if self.phase == 0:
            # set target pos (x, y, z) to 10 cm above cube A
            target_pos = cubeA_pos.copy()
            target_pos[2] += 0.1  # 10cm above cube A
            
            # update controller target
            self.controller.reset(target = target_pos)
            
            # get control signal (delta position command)
            control = self.controller.update(eef_pos[:3], self.dt)
            action[:3] = control
            
            # keep gripper open (last elem of action arr)
            action[-1] = -1.0
            
            # check if close enough to move to next phase
            distance = np.linalg.norm(eef_pos[:3] - target_pos)
            if distance < 0.03:  # within 3cm
                self.phase = 1
        
        # phase 1: lower and grasp cube A
        elif self.phase == 1:
            target_pos = cubeA_pos.copy()
            target_pos[2] += 0.01  # reduced from 0.02 to 0.01 (1cm above, closer to cube)
            
            # update controller target
            self.controller.reset(target=target_pos)
            
            # get control signal
            control = self.controller.update(eef_pos[:3], self.dt)
            action[:3] = control
            
            # check horizontal distance (X, Y) to ensure we're centered over cube
            horizontal_distance = np.linalg.norm(eef_pos[:2] - cubeA_pos[:2])
            vertical_distance = abs(eef_pos[2] - target_pos[2])
            
            # only close gripper when close enough horizontally AND vertically
            if horizontal_distance < 0.015 and vertical_distance < 0.015:  # within 1.5cm
                action[-1] = 1.0  # close gripper
                
                # wait a bit before transitioning (give gripper time to close)
                if not hasattr(self, 'grasp_wait'):
                    self.grasp_wait = 0
                self.grasp_wait += 1
                
                # wait ~15 steps (0.75 second at 20Hz) before lifting (reduced from 20 for faster execution)
                if self.grasp_wait > 15:
                    if self.segmented:
                        self.phase = 10
                        # Same low grasp pose as phase 1 target (existing waypoint, not place-down)
                        self._post_grasp_hold = cubeA_pos.copy()
                        self._post_grasp_hold[2] += 0.01
                    else:
                        self.phase = 2
                    self.grasp_wait = 0
            else:
                # keep gripper open until we're close enough
                action[-1] = -1.0
                if hasattr(self, 'grasp_wait'):
                    self.grasp_wait = 0  # reset if we move away
        
        # phase 2: existing waypoint — hover 10 cm above cube B (before place-down)
        elif self.phase == 2:
            target_pos = cubeB_pos.copy()
            target_pos[2] += 0.1  # 10cm above cube B

            self.controller.reset(target=target_pos)
            control = self.controller.update(eef_pos[:3], self.dt)
            action[:3] = control
            action[-1] = 1.0

            distance = np.linalg.norm(eef_pos[:3] - target_pos)
            if distance < 0.03:
                if self.segmented:
                    self.phase = 11
                    self._hover_hold_target = target_pos.copy()
                else:
                    self.phase = 3

        # phase 10: segmented — hold at grasp pose (no move toward B until begin_hover)
        elif self.phase == 10:
            target_pos = (
                self._post_grasp_hold.copy()
                if self._post_grasp_hold is not None
                else eef_pos[:3]
            )
            self.controller.reset(target=target_pos)
            control = self.controller.update(eef_pos[:3], self.dt)
            action[:3] = control
            action[-1] = 1.0

        # phase 11: segmented — hold above B (no place-down until begin_place)
        elif self.phase == 11:
            target_pos = (
                self._hover_hold_target.copy()
                if self._hover_hold_target is not None
                else eef_pos[:3]
            )
            self.controller.reset(target=target_pos)
            control = self.controller.update(eef_pos[:3], self.dt)
            action[:3] = control
            action[-1] = 1.0

        # phase 3: stack on cube B and release (existing place-down motion)
        elif self.phase == 3:
            target_pos = cubeB_pos.copy()
            target_pos[2] += 0.05  # stack cube A on top of cube B
            
            # update controller target
            self.controller.reset(target=target_pos)
            
            # get control signal
            control = self.controller.update(eef_pos[:3], self.dt)
            action[:3] = control
            
            # open gripper to release cube A
            action[-1] = -1.0

        return action


class IncrementalTeleopPolicy(object):
    """
    Voice-driven small translation in **fixed world axes** (table / viewer frame), plus gripper.

    Translation is **not** tied to the end-effector orientation, so **counterclockwise** /
    **clockwise** rotations do not change what **left** / **right** mean. Axes match common
    robosuite table layouts: **up** / **down** = ±world **Z**; **forward** / **back** = ±**X**
    (same line as nut retreat “back” = −X); **right** / **left** = ±**Y** (same as
    ``DoorPolicy`` pull to the right = +Y).

    **counterclockwise** / **clockwise** use yaw on ``action[5]`` in the same style as
    ``NutAssemblyPolicy`` waypoint 4, but at **half** the per-step magnitude (``±0.05``)
    so each command rotates less.
    """

    # ~half of NutAssemblyPolicy waypoint 4 medium yaw clip (0.1 rad/step) for gentler teleop
    _INCREMENTAL_YAW_PER_STEP = 0.05

    # World-frame unit directions for OSC delta position (unchanged after EE rotation).
    _WORLD_AXIS: dict[str, np.ndarray] = {
        "up": np.array([0.0, 0.0, 1.0]),
        "down": np.array([0.0, 0.0, -1.0]),
        "right": np.array([0.0, 1.0, 0.0]),
        "left": np.array([0.0, -1.0, 0.0]),
        "forward": np.array([1.0, 0.0, 0.0]),
        "back": np.array([-1.0, 0.0, 0.0]),
    }

    def __init__(
        self,
        _obs,
        *,
        delta_per_step: float = 0.048,
        spatial_steps: int = 26,
        rotation_steps: int = 26,
        grip_steps: int = 15,
    ):
        self.delta_per_step = float(delta_per_step)
        self.spatial_steps = int(spatial_steps)
        self.rotation_steps = int(rotation_steps)
        self.grip_steps = int(grip_steps)
        self._pos_clip = 0.14
        self._spatial_cmd: str | None = None
        self._pos_steps = 0
        self._rot_steps = 0
        self._rot_yaw = 0.0
        self._grip_pulse_steps = 0
        self._grip_pulse_cmd = -1.0
        self._gripper_hold = -1.0

    def set_command(self, cmd: str) -> None:
        """Queue one burst for a recognized incremental keyword."""
        c = " ".join(cmd.lower().split())
        spatial = {"up", "down", "left", "right", "forward", "back"}
        if c in spatial:
            self._rot_steps = 0
            self._rot_yaw = 0.0
            self._spatial_cmd = c
            self._pos_steps = self.spatial_steps
            return
        if c == "counterclockwise":
            self._spatial_cmd = None
            self._pos_steps = 0
            self._rot_yaw = -self._INCREMENTAL_YAW_PER_STEP
            self._rot_steps = self.rotation_steps
            return
        if c == "clockwise":
            self._spatial_cmd = None
            self._pos_steps = 0
            self._rot_yaw = self._INCREMENTAL_YAW_PER_STEP
            self._rot_steps = self.rotation_steps
            return
        if c == "open":
            self._spatial_cmd = None
            self._pos_steps = 0
            self._rot_steps = 0
            self._rot_yaw = 0.0
            self._grip_pulse_cmd = -1.0
            self._grip_pulse_steps = self.grip_steps
            return
        if c == "close":
            self._spatial_cmd = None
            self._pos_steps = 0
            self._rot_steps = 0
            self._rot_yaw = 0.0
            self._grip_pulse_cmd = 1.0
            self._grip_pulse_steps = self.grip_steps
            return

    def get_action(self, _obs):
        action = np.zeros(7)
        dirs = self._WORLD_AXIS

        # NutAssemblyPolicy waypoint 4: yaw-only (action[3:6] roll=0, pitch=0, yaw=control)
        if self._rot_steps > 0:
            action[:3] = 0.0
            action[3] = 0.0
            action[4] = 0.0
            action[5] = float(
                np.clip(
                    self._rot_yaw,
                    -self._INCREMENTAL_YAW_PER_STEP,
                    self._INCREMENTAL_YAW_PER_STEP,
                )
            )
            self._rot_steps -= 1
            if self._rot_steps <= 0:
                self._rot_yaw = 0.0
        elif self._pos_steps > 0 and self._spatial_cmd is not None:
            d = dirs.get(self._spatial_cmd)
            if d is not None:
                delta = np.asarray(d, dtype=np.float64).reshape(3) * self.delta_per_step
                c = self._pos_clip
                action[:3] = np.clip(delta, -c, c)
            self._pos_steps -= 1
            if self._pos_steps <= 0:
                self._spatial_cmd = None

        if self._grip_pulse_steps > 0:
            action[6] = self._grip_pulse_cmd
            self._grip_pulse_steps -= 1
            self._gripper_hold = self._grip_pulse_cmd
        else:
            action[6] = self._gripper_hold

        return action


class NutAssemblyPolicy(object):
    """
    Policy for nut assembly (approach handle, grasp, lift, align, place on peg).

    **Full run** (``segmented=False``): waypoints 0→6 continuously, then round nut.

    **Segmented** (``segmented=True``): voice **grab** runs 0→1→2 then hold (**waypoint 10**);
    **hover** continues 3→4→5 then hold (**waypoint 11**); **place** runs **waypoint 6**
    (release). After the square nut is placed, the env switches to the round nut and pauses at
    **waypoint -2** until **grab** again; then ``start_next_grab_segment`` runs the same
    grab→hover→place pattern for the round nut.
    """
    def __init__(self, obs, segmented=False):
        """
        Args:
            obs (dict): Includes 'SquareNut_pos', 'SquareNut_quat', etc.
            segmented: If True, pause after grasp and after peg-hover until ``begin_hover`` /
                ``begin_place`` (grab → hover → place voice flow).
        """
        # get current end-effector position
        eef_pos = obs["robot0_eef_pos"]
        self.segmented = bool(segmented)
        self._post_grasp_hold = None
        self._hover_hold_target = None
        
        # save original gripper quaternion for alignment after lift
        self.home_q = obs["robot0_eef_quat_site"].copy()
        
        # initialize PID controller for position
        self.pos_controller = PID(kp=10.0, ki=0.0, kd=5.0, target=eef_pos[:3])
        
        # initialize PID controller for rotation (yaw control)
        # target yaw is 0.0 (aligned with nut)
        self.rot_controller = PID(kp=0.1, ki=0.0, kd=0.05, target=np.array([0.0]))
        
        # initialize PID controllers for rotation (roll, pitch, yaw) - not currently used but kept for future use
        # use lower gains for smoother rotation control
        self.rot_controller_roll = PID(kp=0.05, ki=0.0, kd=0.02, target=np.array([0.0]))
        self.rot_controller_pitch = PID(kp=0.05, ki=0.0, kd=0.02, target=np.array([0.0]))
        self.rot_controller_yaw = PID(kp=0.05, ki=0.0, kd=0.02, target=np.array([0.0]))
        
        self.dt = 0.05
        self.waypoint = 0  # -1 = retreat backwards 10cm (after switching to round nut), 0 = move to nut center, 1 = move to handle, 2 = move down and grasp handle, 3 = lift vertically to 15cm above peg top, 4 = rotate horizontally (yaw only) to align nut, 5 = move nut center above peg center, 6 = release gripper to drop nut (repeats for round nut after square nut)
        
        # default downward rotation for the hand (pointing down)
        self.DOWNWARD_ROTATION = R.from_euler('x', 180, degrees=True)
        
        # handle offset distance from nut center
        self.HANDLE_OFFSET = 0.065
        
        # thresholds - relaxed for faster execution (was taking 4+ min, need <60s)
        self.POS_THRESHOLD = 0.04  # 4cm for waypoint 0 (relaxed from 3cm)
        self.POS_THRESHOLD_RETREAT = 0.03  # 3cm for waypoint -1 (retreat) (relaxed from 2cm)
        self.POS_THRESHOLD_WAYPOINT1 = 0.025  # 2.5cm for waypoint 1 (relaxed from 1cm - was very tight)
        self.POS_THRESHOLD_WAYPOINT2 = 0.025  # 2.5cm for waypoint 2 (grasping) (relaxed from 1.5cm)
        self.POS_THRESHOLD_WAYPOINT2_GRASPED = 0.03  # 3cm for waypoint 2 transition when already grasped (relaxed from 2cm)
        self.POS_THRESHOLD_WAYPOINT3 = 0.04  # 4cm for waypoint 3 (lifting) (relaxed from 3cm)
        self.POS_THRESHOLD_WAYPOINT4 = 0.04  # 4cm for waypoint 4 (transporting to peg) (relaxed from 3cm)
        self.POS_THRESHOLD_WAYPOINT5 = 0.025  # 2.5cm for waypoint 5 (positioning nut above peg) (relaxed from 1.5cm)
        self.ROT_THRESHOLD = 0.15  # rotation threshold (radians, ~14.3 degrees) (widened to match handle direction faster)
        
        # retreat distance (10cm backwards)
        self.RETREAT_DISTANCE = 0.10  # 10cm
        
        # grip offset: go slightly below handle for tighter grip
        self.GRIP_OFFSET_BELOW = 0.015  # 1.5cm below handle
        
        # waypoint 5 offset: hover slightly to the left and forward before releasing
        self.WAYPOINT5_LEFT_OFFSET = 0.015  # 1cm to the left (negative y direction)
        self.WAYPOINT5_FORWARD_OFFSET = 0.015  # 1cm forward (positive x direction)
        self.WAYPOINT5_RIGHT_OFFSET = 0.01  # 0.5cm to the right (positive y direction)
        
        # track gripper state
        self.grasp_wait = 0
        self.gripper_closed = False
        
        # track which nut we're currently working on (start with square, then do round)
        self.current_nut = "Square"  # start with square nut
        
        # determine nut type based on current nut
        self.nut_type = self.current_nut
        
        # hardcoded peg positions
        self.PEG1_POS = np.array([0.23, 0.105, 0.85])
        self.PEG2_POS = np.array([0.23, -0.100, 0.85])
        
        # determine which peg corresponds to current nut
        # SquareNut -> Peg1, RoundNut -> Peg2
        if self.nut_type == "Square":
            self.target_peg_pos = self.PEG1_POS.copy()
        else:  # RoundNut
            self.target_peg_pos = self.PEG2_POS.copy()
        
        # peg orientation (assume vertical, square peg aligned with world axes)
        # For square peg, we want the nut's square face aligned
        # Using identity quaternion [1, 0, 0, 0] as base (can be adjusted if peg has specific orientation)
        self.target_peg_quat = np.array([1, 0, 0, 0])  # [w, x, y, z] format
        
    def quat_to_rotation(self, quat):
        """
        Convert quaternion to scipy Rotation object.
        Assumes robosuite format [w, x, y, z] and converts to scipy format [x, y, z, w].

        Generated with Gemini with prompt: "given this code, generate a function that converts a quaternion from robosuite format
        to scipy Rotation object"
        
        Args:
            quat: Quaternion array [w, x, y, z] (robosuite format)
        
        Returns:
            scipy Rotation object
        """
        quat = np.array(quat)
        if len(quat) != 4:
            return R.identity()
        
        # check if quaternion is valid (non-zero norm)
        if np.linalg.norm(quat) < 1e-6:
            return R.identity()  # return identity if invalid
        
        # normalize quaternion
        quat = quat / np.linalg.norm(quat)
        
        # robosuite uses [w, x, y, z], scipy uses [x, y, z, w]
        # convert: [w, x, y, z] -> [x, y, z, w]
        return R.from_quat([quat[1], quat[2], quat[3], quat[0]])
    
    
    def calculate_handle_position(self, nut_pos, nut_quat, handle_offset_dist=0.065):
        """
        Calculate handle position from nut center using rotation matrix approach.
        Handle is at fixed offset along nut's local +x axis.

        Generated with Gemini with prompt: "make a function that calculates the handle position from
        the nut center given the above"
        
        Args:
            nut_pos: Position of the nut center [x, y, z]
            nut_quat: Quaternion of the nut [w, x, y, z] (robosuite format)
            handle_offset_dist: Distance from nut center to handle (default 0.065m)
        
        Returns:
            Handle position [x, y, z]
        """
        # convert quaternion to rotation matrix using robosuite's transform utils
        rotation_matrix = T.quat2mat(nut_quat)
        
        # handle offset in nut's local frame (along local +x axis)
        local_handle_offset = np.array([handle_offset_dist, 0, 0])
        
        # rotate handle offset to world frame using rotation matrix
        world_handle_offset = rotation_matrix.dot(local_handle_offset)
        
        # calculate handle position in world frame
        handle_world_pos = nut_pos + world_handle_offset
        
        return handle_world_pos
    
    def switch_to_round_nut(self, obs):
        """
        Switch from square nut to round nut and reset all waypoint state.
        Called after successfully completing square nut assembly.

        Generated with Gemini with prompt: "given this code, generate a function that handles the logic
        of switching from square nut to round nut and resetting respective states. goal: reuse the waypoints i
        already made"

        returns void
        """
        print(f"\n>>> SWITCHING FROM SQUARE NUT TO ROUND NUT <<<")
        self.current_nut = "Round"
        self.nut_type = "Round"
        self.target_peg_pos = self.PEG2_POS.copy()  # Round nut goes to Peg2
        
        eef_pos = obs["robot0_eef_pos"]
        # Full run: retreat (-1). Segmented: pause at -2 until voice **grab** starts round-nut segment.
        if self.segmented:
            self.waypoint = -2
        else:
            self.waypoint = -1
            self.retreat_start_pos = eef_pos[:3].copy()
        
        # Reset all waypoint-specific state
        if hasattr(self, 'waypoint3_initial_pos'):
            del self.waypoint3_initial_pos
        if hasattr(self, 'waypoint3_final_pos'):
            del self.waypoint3_final_pos
        if hasattr(self, 'waypoint5_nut_to_eef_offset'):
            del self.waypoint5_nut_to_eef_offset
        if hasattr(self, 'waypoint5_final_pos'):
            del self.waypoint5_final_pos
        if hasattr(self, '_waypoint4_transition_debug'):
            del self._waypoint4_transition_debug
        if hasattr(self, '_waypoint5_transition_debug'):
            del self._waypoint5_transition_debug
        if hasattr(self, '_waypoint4_rot_initialized'):
            del self._waypoint4_rot_initialized
        
        # Reset gripper state
        self.gripper_closed = False
        self.grasp_wait = 0
        
        # Reset controllers
        eef_pos = obs["robot0_eef_pos"]
        self.pos_controller.reset(target=eef_pos[:3])
        self.rot_controller.reset(target=np.array([0.0]))
        
        # Save new home orientation for round nut
        self.home_q = obs["robot0_eef_quat_site"].copy()
        
        print(f"  Switched to Round nut")
        print(f"  Target peg: Peg2 at [{self.target_peg_pos[0]:.4f}, {self.target_peg_pos[1]:.4f}, {self.target_peg_pos[2]:.4f}]")
        if self.segmented:
            print(
                '  Segmented: say "grab" to run grab → hover → place on the round nut.',
                flush=True,
            )
        else:
            print(
                "  Starting at waypoint -1 (retreat) - will retreat 10cm backwards before approaching round nut"
            )

    def start_next_grab_segment(self, obs) -> None:
        """After voice **grab** at waypoint -2: start round-nut retreat (-1) and approach."""
        if not self.segmented or self.waypoint != -2:
            return
        eef_pos = obs["robot0_eef_pos"]
        self.retreat_start_pos = eef_pos[:3].copy()
        self.waypoint = -1

    def begin_hover(self) -> None:
        """After voice **hover**: leave post-grasp hold and run waypoints 3→4→5 (lift, yaw, peg hover)."""
        if self.segmented and self.waypoint == 10:
            for attr in ("waypoint3_initial_pos", "waypoint3_final_pos"):
                if hasattr(self, attr):
                    delattr(self, attr)
            self.waypoint = 3

    def begin_place(self) -> None:
        """After voice **place**: leave peg-hover hold and run waypoint 6 (release)."""
        if self.segmented and self.waypoint == 11:
            if self._hover_hold_target is not None:
                self.waypoint5_final_pos = self._hover_hold_target.copy()
            self.waypoint = 6

    def segment_grab_done(self, obs) -> bool:
        """Segmented: grasp stable at post-grasp hold (waypoint 10)."""
        if not self.segmented or self.waypoint != 10 or self._post_grasp_hold is None:
            return False
        eef = obs["robot0_eef_pos"]
        return np.linalg.norm(eef[:3] - self._post_grasp_hold) < 0.03

    def segment_hover_done(self, obs) -> bool:
        """Segmented: reached hold above peg (waypoint 11), before place."""
        if not self.segmented or self.waypoint != 11 or self._hover_hold_target is None:
            return False
        eef = obs["robot0_eef_pos"]
        return np.linalg.norm(eef[:3] - self._hover_hold_target) < 0.03
        
    def get_action(self, obs):
        """
        Returns:
            np.ndarray: 7D action (Delta-X, Delta-Y, Delta-Z, Axis-Angle [3], Gripper).
        """
        action = np.zeros(7)
        
        # get current end-effector position
        eef_pos = obs["robot0_eef_pos"]

        if self.waypoint == -2:
            # Segmented: between nuts — hold still, gripper open, until start_next_grab_segment
            action[6] = -1.0
            return action
        
        # get nut position and quaternion (use current_nut to track which nut we're working on)
        nut_pos_key = f"{self.current_nut}Nut_pos"
        nut_quat_key = f"{self.current_nut}Nut_quat"
        
        nut_pos = obs.get(nut_pos_key, np.array([0.2, 0.1, 0.8]))
        nut_quat = obs.get(nut_quat_key, np.array([1, 0, 0, 0]))
        
        # calculate handle position (at fixed offset along nut's local +x axis)
        handle_pos = self.calculate_handle_position(nut_pos, nut_quat)
        
        # determine target position based on waypoint
        if self.waypoint == -1:
            # waypoint -1: retreat backwards 10cm to avoid circular peg blocking the path
            # Move backwards in negative x direction (away from pegs)
            if not hasattr(self, 'retreat_start_pos'):
                # Fallback: use current position if not stored
                self.retreat_start_pos = eef_pos[:3].copy()
            target_pos = self.retreat_start_pos.copy()
            target_pos[0] -= self.RETREAT_DISTANCE  # move backwards 10cm in negative x direction
        elif self.waypoint == 0:
            # waypoint 0: move to nut center (5cm above) and align rotation
            target_pos = nut_pos.copy()
            target_pos[2] += 0.05  # 5cm above nut center
        elif self.waypoint == 1:
            # waypoint 1: move directly to handle position (5cm above handle)
            target_pos = handle_pos.copy()
            target_pos[2] += 0.05  # 5cm above handle
        elif self.waypoint == 2:
            # waypoint 2: move down to handle position (slightly below for tight grip)
            target_pos = handle_pos.copy()
            target_pos[2] -= self.GRIP_OFFSET_BELOW  # go slightly below handle
        elif self.waypoint == 3:
            # waypoint 3: immediately raise vertically to 15cm above the plane containing the top face of the peg
            # Keep x,y fixed from when we entered waypoint 3, only raise z to peg_top + 0.15m
            # Store initial x,y position when transitioning to waypoint 3 (done in transition logic)
            if not hasattr(self, 'waypoint3_initial_pos'):
                # If not stored yet, use current position (should only happen on first step of waypoint 3)
                self.waypoint3_initial_pos = eef_pos[:3].copy()
            peg_top_z = self.target_peg_pos[2]  # peg top is at z = 0.85
            target_z = peg_top_z + 0.15  # 15cm above peg top
            target_pos = self.waypoint3_initial_pos.copy()  # use fixed x,y from start of waypoint 3
            target_pos[2] = target_z  # only change z to be 15cm above peg top
        elif self.waypoint == 4:
            # waypoint 4: rotate horizontally (yaw only) to align nut - keep position fixed from waypoint 3
            # Store the waypoint 3 position when we transition
            if not hasattr(self, 'waypoint3_final_pos'):
                # If not stored yet, use current position (should be at 15cm above peg top)
                self.waypoint3_final_pos = eef_pos[:3].copy()
            target_pos = self.waypoint3_final_pos.copy()  # keep same position, only rotate horizontally
        elif self.waypoint == 5:
            # waypoint 5: move nut center above peg center
            # Target: position end-effector such that nut center is at peg x, y
            # Use stored offset from nut center to end-effector (calculated at transition)
            
            # Get offset from nut to end-effector (stored during transition)
            if not hasattr(self, 'waypoint5_nut_to_eef_offset'):
                # Fallback: calculate offset from current positions if not stored
                nut_to_eef_offset = eef_pos[:3] - nut_pos[:3]
            else:
                nut_to_eef_offset = self.waypoint5_nut_to_eef_offset
            
            # Calculate target z to ensure nut is high enough above peg (nut hangs below gripper)
            # We want nut center to be at least 15cm above peg top
            peg_top_z = self.target_peg_pos[2]  # peg top is at z = 0.85
            min_nut_z = peg_top_z + 0.15  # nut should be at least 15cm above peg top
            
            # Calculate what gripper z should be to achieve this
            # nut_z = eef_z - nut_to_eef_offset[2]
            # So: eef_z = nut_z + nut_to_eef_offset[2]
            # We want nut_z >= min_nut_z, so:
            target_z = min_nut_z + nut_to_eef_offset[2]
            
            # Also ensure we're at least as high as waypoint 3 (safety check)
            if hasattr(self, 'waypoint3_final_pos'):
                target_z = max(target_z, self.waypoint3_final_pos[2])
            
            # Target end-effector position: peg x, y + offset, so nut center (eef - offset) is at peg x, y
            # Add leftward offset (negative y direction), forward offset (positive x direction), and right offset (positive y direction) before releasing
            target_pos = np.array([
                self.target_peg_pos[0] + nut_to_eef_offset[0] + self.WAYPOINT5_FORWARD_OFFSET,  # peg x + offset + forward offset
                self.target_peg_pos[1] + nut_to_eef_offset[1] - self.WAYPOINT5_LEFT_OFFSET + self.WAYPOINT5_RIGHT_OFFSET,  # peg y + offset - left offset + right offset
                target_z  # ensure nut is high enough above peg top
            ])
        elif self.waypoint == 10:
            # Segmented: hold at grasp pose (same target as waypoint 2) until begin_hover
            target_pos = (
                self._post_grasp_hold.copy()
                if self._post_grasp_hold is not None
                else eef_pos[:3]
            )
        elif self.waypoint == 11:
            # Segmented: hold at peg-hover pose (waypoint 5 target) until begin_place
            target_pos = (
                self._hover_hold_target.copy()
                if self._hover_hold_target is not None
                else eef_pos[:3]
            )
        elif self.waypoint == 6:
            # waypoint 6: release gripper - keep position fixed from waypoint 5
            if not hasattr(self, 'waypoint5_final_pos'):
                # If not stored yet, use current position (should be above peg center)
                self.waypoint5_final_pos = eef_pos[:3].copy()
            target_pos = self.waypoint5_final_pos.copy()  # keep same position, just open gripper
        else:
            # fallback: stay at current position
            target_pos = eef_pos[:3].copy()
        
        # check if rotation is aligned (for stopping control)
        rot_aligned = True
        current_yaw = 0.0
        rot_error = 0.0  # initialize rotation error
        yaw_error = 0.0  # initialize yaw error for waypoint 4
        
        # Rotation control for waypoint 0 and waypoint 4
        # No rotation control for waypoint -1 (retreat) - keep current orientation
        if self.waypoint == -1:
            # no rotation control during retreat
            action[3:6] = np.zeros(3)
        elif self.waypoint == 4:
            # waypoint 4: align gripper back to original home orientation (yaw only)
            # After lifting, restore original gripper yaw orientation
            
            # Get current end-effector quaternion
            eef_quat = obs["robot0_eef_quat_site"]
            
            # Extract yaw from home quaternion and current eef quaternion
            _, _, home_yaw = T.mat2euler(T.quat2mat(self.home_q))
            _, _, eef_yaw = T.mat2euler(T.quat2mat(eef_quat))
            
            # Calculate yaw error using wrap-around formula (handles 180° ambiguity)
            # This formula ensures we always take the shortest rotation path
            yaw_error = (home_yaw - eef_yaw + np.pi) % (2 * np.pi) - np.pi
            
            # Check if rotation is aligned - tighter threshold for proper alignment before moving to peg
            waypoint4_rot_threshold = 0.08  # ~4.6 degrees (tighter for proper alignment)
            rot_aligned = abs(yaw_error) < waypoint4_rot_threshold
            
            # Apply yaw control only (horizontal rotation)
            # Increased gains for faster rotation in the air (no contact constraints)
            if not rot_aligned:
                # Use proportional control with gain (similar to student's approach)
                # Apply gain to the wrapped error and clip
                yaw_gain = 0.25  # increased from 0.2 for faster rotation to reach alignment
                yaw_control = yaw_gain * yaw_error
                
                # Apply deadband and clipping to prevent oscillation
                # Smaller deadband to allow fine adjustments for proper alignment
                if abs(yaw_error) < 0.03:  # deadband for very small errors (< 1.7°)
                    yaw_control = 0.0
                else:
                    # Allow stronger control signal for larger errors, but still clip for safety
                    if abs(yaw_error) > 0.15:  # large error - use stronger control
                        yaw_control = np.clip(yaw_control, -0.15, 0.15)
                    else:  # medium error - moderate control
                        yaw_control = np.clip(yaw_control, -0.1, 0.1)
                
                action[5] = yaw_control  # yaw only
                action[3] = 0.0  # no roll
                action[4] = 0.0  # no pitch
            else:
                # Stop rotation control once aligned
                action[3:6] = np.zeros(3)
        elif self.waypoint == 0:
            # rotation control for waypoint 0: align with nut
            nut_to_eef_quat_key = f"{self.nut_type}Nut_to_robot0_eef_quat"
            if nut_to_eef_quat_key in obs and np.sum(obs[nut_to_eef_quat_key]) != 0:
                # extract yaw from relative quaternion (nut to end-effector)
                nut_to_eef_quat = obs[nut_to_eef_quat_key]
                
                # handle quaternion format: scipy expects [x, y, z, w], robosuite might use [w, x, y, z]
                # try direct format first (as user's code does)
                try:
                    current_yaw = R.from_quat(nut_to_eef_quat).as_euler('xyz')[2]
                except:
                    # if that fails, convert from [w, x, y, z] to [x, y, z, w]
                    quat_converted = np.array([nut_to_eef_quat[1], nut_to_eef_quat[2], nut_to_eef_quat[3], nut_to_eef_quat[0]])
                    current_yaw = R.from_quat(quat_converted).as_euler('xyz')[2]
                
                # normalize yaw to [-π, π] range to handle wrap-around
                # this ensures angles near ±π are handled correctly
                current_yaw = np.arctan2(np.sin(current_yaw), np.cos(current_yaw))
                
                # check if rotation is aligned (close to 0, accounting for wrap-around)
                # the normalized yaw is already in [-π, π], so we just check if it's close to 0
                rot_aligned = abs(current_yaw) < self.ROT_THRESHOLD
                
                # rotation control: only apply in waypoint 0 (when aligning at center)
                # disable rotation control in waypoint 1, 2, and 3 (when moving to handle) to avoid interference
                if self.waypoint == 0:
                    if not rot_aligned:
                        # use PID controller for rotation control
                        # target is 0.0 (aligned), update with current normalized yaw
                        yaw_control = self.rot_controller.update(np.array([current_yaw]), self.dt)
                        # clip the control output to prevent excessive rotation commands
                        yaw_control = np.clip(yaw_control[0], -0.05, 0.05)
                        action[5] = yaw_control
                    else:
                        # stop rotation control once aligned and reset PID controller
                        action[5] = 0.0
                        self.rot_controller.reset(target=np.array([0.0]))
                else:
                    # waypoint 1, 2, and 3: disable rotation control to allow smooth movement
                    action[3:6] = np.zeros(3)
            else:
                # no rotation control if quaternion not available
                action[3:6] = np.zeros(3)
        
        # position control: move to target position
        # calculate end-effector distance to target
        eef_distance = np.linalg.norm(eef_pos[:3] - target_pos)
        
        # use appropriate threshold based on waypoint
        if self.waypoint == -1:
            pos_reached = eef_distance < self.POS_THRESHOLD_RETREAT
            pos_distance = eef_distance  # for debug output
        elif self.waypoint == 1:
            pos_reached = eef_distance < self.POS_THRESHOLD_WAYPOINT1
            pos_distance = eef_distance  # for debug output
        elif self.waypoint == 2:
            pos_reached = eef_distance < self.POS_THRESHOLD_WAYPOINT2
            pos_distance = eef_distance  # for debug output
        elif self.waypoint == 3:
            pos_reached = eef_distance < self.POS_THRESHOLD_WAYPOINT3
            pos_distance = eef_distance  # for debug output
        elif self.waypoint == 4:
            # in waypoint 4, we don't move position - only rotate horizontally
            # Position is already reached (we're keeping the same position from waypoint 3)
            pos_reached = True  # position doesn't change in waypoint 4
            pos_distance = 0.0  # no position movement
        elif self.waypoint == 5:
            pos_reached = eef_distance < self.POS_THRESHOLD_WAYPOINT5  # use tighter threshold for precision
            pos_distance = eef_distance  # for debug output
        elif self.waypoint == 10:
            pos_reached = eef_distance < self.POS_THRESHOLD_WAYPOINT2
            pos_distance = eef_distance
        elif self.waypoint == 11:
            pos_reached = eef_distance < self.POS_THRESHOLD_WAYPOINT5
            pos_distance = eef_distance
        elif self.waypoint == 6:
            # in waypoint 6, we don't move position - only open gripper
            # Position is already reached (we're keeping the same position from waypoint 5)
            pos_reached = True  # position doesn't change in waypoint 6
            pos_distance = 0.0  # no position movement
        else:
            pos_reached = eef_distance < self.POS_THRESHOLD
            pos_distance = eef_distance  # for debug output
        
        # in waypoint -1, move backwards to retreat position
        # in waypoint 0, stop only when both position AND rotation are aligned
        # in waypoint 1, 2, and 3, stop when position is reached
        # in waypoint 4, no position movement (rotation only)
        if self.waypoint == -1:
            # waypoint -1: retreat backwards 10cm (gripper open - can move faster)
            if not pos_reached:
                # reset controller if target has changed
                target_diff = np.linalg.norm(self.pos_controller.target - target_pos)
                if target_diff > 0.001:  # if target changed by more than 1mm, reset
                    self.pos_controller.reset(target=target_pos)
                pos_control = self.pos_controller.update(eef_pos[:3], self.dt)
                pos_control = np.clip(pos_control, -0.15, 0.15)  # faster movement when gripper open
                action[:3] = pos_control
            else:
                # stop position movement once at retreat position
                action[:3] = np.zeros(3)
        elif self.waypoint == 0:
            # waypoint 0: stop only when both position and rotation are aligned (gripper open - can move faster)
            if not (pos_reached and rot_aligned):
                self.pos_controller.reset(target=target_pos)
                pos_control = self.pos_controller.update(eef_pos[:3], self.dt)
                pos_control = np.clip(pos_control, -0.15, 0.15)  # faster movement when gripper open
                action[:3] = pos_control
            else:
                # stop position movement once aligned
                action[:3] = np.zeros(3)
        elif self.waypoint == 4:
            # waypoint 4: rotation only - no position movement
            # Keep position fixed from waypoint 3
            action[:3] = np.zeros(3)  # no position movement, only horizontal rotation
        elif self.waypoint == 5:
            # waypoint 5: move nut center above peg center
            if not pos_reached:
                # reset controller if target has changed
                target_diff = np.linalg.norm(self.pos_controller.target - target_pos)
                if target_diff > 0.001:  # if target changed by more than 1mm, reset
                    self.pos_controller.reset(target=target_pos)
                pos_control = self.pos_controller.update(eef_pos[:3], self.dt)
                # Use tighter clipping for precision - reduce control signal when close to target
                if pos_distance < 0.05:  # within 5cm, use finer control
                    pos_control = np.clip(pos_control, -0.05, 0.05)
                else:
                    pos_control = np.clip(pos_control, -0.1, 0.1)
                action[:3] = pos_control
            else:
                # stop position movement once aligned
                action[:3] = np.zeros(3)
        elif self.waypoint == 10:
            target_diff = np.linalg.norm(self.pos_controller.target - target_pos)
            if target_diff > 0.001:
                self.pos_controller.reset(target=target_pos)
            pos_control = self.pos_controller.update(eef_pos[:3], self.dt)
            pos_control = np.clip(pos_control, -0.1, 0.1)
            action[:3] = pos_control
        elif self.waypoint == 11:
            target_diff = np.linalg.norm(self.pos_controller.target - target_pos)
            if target_diff > 0.001:
                self.pos_controller.reset(target=target_pos)
            pos_control = self.pos_controller.update(eef_pos[:3], self.dt)
            if pos_distance < 0.05:
                pos_control = np.clip(pos_control, -0.05, 0.05)
            else:
                pos_control = np.clip(pos_control, -0.1, 0.1)
            action[:3] = pos_control
        elif self.waypoint == 6:
            # waypoint 6: release gripper - no position movement
            # Keep position fixed from waypoint 5
            action[:3] = np.zeros(3)  # no position movement, only open gripper
        else:
            # waypoint 1, 2, and 3: move to target, stop when position is reached
            # reset controller if target has changed (e.g., just transitioned to new waypoint)
            # check if controller target is significantly different from current target_pos
            target_diff = np.linalg.norm(self.pos_controller.target - target_pos)
            if target_diff > 0.001:  # if target changed by more than 1mm, reset
                if self.waypoint == 2 or self.waypoint == 3:
                    print(f"  [Waypoint {self.waypoint}] Resetting controller: target_diff={target_diff:.4f}")
                    print(f"    Old controller target: {self.pos_controller.target}")
                    print(f"    New target_pos: {target_pos}")
                self.pos_controller.reset(target=target_pos)
            
            if not pos_reached:
                pos_control = self.pos_controller.update(eef_pos[:3], self.dt)
                # Faster movement for waypoint 1 (gripper open)
                # Keep waypoint 2 (grasping) and waypoint 3 (lifting) slower to prevent nut from slipping
                if self.waypoint == 1:
                    pos_control = np.clip(pos_control, -0.15, 0.15)  # faster when gripper open
                elif self.waypoint == 3:
                    pos_control = np.clip(pos_control, -0.1, 0.1)  # slower for lifting to prevent nut from slipping
                else:  # waypoint 2 - keep slower for precision when grasping
                    pos_control = np.clip(pos_control, -0.1, 0.1)
                action[:3] = pos_control
                
                # debug output for waypoint 2 and 3 position control
                if (self.waypoint == 2 or self.waypoint == 3) and not hasattr(self, f'_waypoint{self.waypoint}_pos_control_debug'):
                    setattr(self, f'_waypoint{self.waypoint}_pos_control_debug', 0)
                if self.waypoint == 2 or self.waypoint == 3:
                    debug_counter = getattr(self, f'_waypoint{self.waypoint}_pos_control_debug', 0)
                    debug_counter += 1
                    setattr(self, f'_waypoint{self.waypoint}_pos_control_debug', debug_counter)
                    if debug_counter % 20 == 0:  # print every 20 steps
                        print(f"\n=== Waypoint {self.waypoint} Position Control (step {debug_counter}) ===")
                        print(f"  eef_pos: [{eef_pos[0]:.4f}, {eef_pos[1]:.4f}, {eef_pos[2]:.4f}]")
                        print(f"  target_pos: [{target_pos[0]:.4f}, {target_pos[1]:.4f}, {target_pos[2]:.4f}]")
                        print(f"  controller_target: [{self.pos_controller.target[0]:.4f}, {self.pos_controller.target[1]:.4f}, {self.pos_controller.target[2]:.4f}]")
                        print(f"  pos_distance: {pos_distance:.4f} m ({pos_distance*100:.2f} cm)")
                        print(f"  pos_reached: {pos_reached}")
                        print(f"  pos_control (clipped): {pos_control}")
                        print(f"  action[:3]: {action[:3]}")
            else:
                # stop position movement once at target
                action[:3] = np.zeros(3)
                if self.waypoint == 2 or self.waypoint == 3:
                    print(f"  [Waypoint {self.waypoint}] Position reached! Stopping movement.")
                    print(f"    Final eef_pos: [{eef_pos[0]:.4f}, {eef_pos[1]:.4f}, {eef_pos[2]:.4f}]")
                    print(f"    Final target_pos: [{target_pos[0]:.4f}, {target_pos[1]:.4f}, {target_pos[2]:.4f}]")
        
        # roll and pitch control handled in rotation control section above
        
        # gripper control: open in waypoint -1, 0 and 1, close in waypoint 2 when close enough, keep closed in waypoint 3, 4, and 5, open in waypoint 6
        if self.waypoint == -1:
            # keep gripper open during retreat
            action[6] = -1.0
        elif self.waypoint == 2:
            # in waypoint 2, close gripper when close enough to handle
            horizontal_distance = np.linalg.norm(eef_pos[:2] - handle_pos[:2])
            vertical_distance = abs(eef_pos[2] - (handle_pos[2] - self.GRIP_OFFSET_BELOW))
            
            # close gripper when close enough horizontally AND vertically
            # Tighter threshold for better grip, especially for round nut
            if horizontal_distance < 0.025 and vertical_distance < 0.025:  # within 2.5cm (tighter for better grip)
                action[6] = 1.0  # close gripper
                self.gripper_closed = True
                self.grasp_wait += 1
            else:
                # keep gripper open until close enough
                action[6] = -1.0
                if hasattr(self, 'grasp_wait'):
                    self.grasp_wait = 0  # reset if we move away
        elif self.waypoint == 3 or self.waypoint == 4 or self.waypoint == 5:
            # in waypoint 3, 4, and 5, keep gripper closed (already gripping)
            action[6] = 1.0
        elif self.waypoint == 10 or self.waypoint == 11:
            action[6] = 1.0
        elif self.waypoint == 6:
            # in waypoint 6, open gripper to release nut
            action[6] = -1.0
        else:
            # keep gripper open in waypoint 0 and 1
            action[6] = -1.0
        
        # check waypoint completion and advance
        # advance from waypoint -1 to waypoint 0 when retreat position is reached
        if self.waypoint == -1:
            if pos_reached:
                # once retreated backwards, switch to moving to round nut center
                print(f"\n>>> TRANSITIONING FROM WAYPOINT -1 (RETREAT) TO WAYPOINT 0 <<<")
                print(f"  Retreat complete, now moving to round nut center")
                self.waypoint = 0
                # reset position controller with round nut center target (5cm above)
                target_pos_nut = nut_pos.copy()
                target_pos_nut[2] += 0.05  # 5cm above nut center
                self.pos_controller.reset(target=target_pos_nut)
        # advance from waypoint 0 to waypoint 1 when both position and rotation are aligned
        elif self.waypoint == 0:
            if pos_reached and rot_aligned:
                # once at nut center AND rotation is aligned, switch to moving to handle
                self.waypoint = 1
                # reset rotation controller when transitioning to waypoint 1
                self.rot_controller.reset(target=np.array([0.0]))
                # reset position controller with handle target (5cm above handle)
                # use the handle_pos already calculated at the beginning of the function
                target_pos_handle = handle_pos.copy()
                target_pos_handle[2] += 0.05  # 5cm above handle
                self.pos_controller.reset(target=target_pos_handle)
        # advance from waypoint 1 to waypoint 2 when position is reached
        elif self.waypoint == 1:
            if pos_reached:
                # once at handle (5cm above), switch to moving down to handle
                self.waypoint = 2
                # reset position controller with handle target (slightly below handle)
                target_pos_grip = handle_pos.copy()
                target_pos_grip[2] -= self.GRIP_OFFSET_BELOW
                self.pos_controller.reset(target=target_pos_grip)
                # reset gripper state
                self.grasp_wait = 0
                self.gripper_closed = False
        # advance from waypoint 2 to waypoint 3 when gripper is closed and position is reached
        elif self.waypoint == 2:
            # debug output for waypoint 2 transition check
            if not hasattr(self, '_waypoint2_transition_debug'):
                self._waypoint2_transition_debug = 0
            self._waypoint2_transition_debug += 1
            if self._waypoint2_transition_debug % 10 == 0:  # print every 10 steps
                print(f"\n=== Waypoint 2 Transition Check (step {self._waypoint2_transition_debug}) ===")
                print(f"  pos_reached: {pos_reached} (distance: {pos_distance:.4f} m, threshold: {self.POS_THRESHOLD_WAYPOINT2:.4f} m)")
                print(f"  gripper_closed: {self.gripper_closed}")
                print(f"  grasp_wait: {self.grasp_wait} (need > 15)")
                print(f"  eef_pos: [{eef_pos[0]:.4f}, {eef_pos[1]:.4f}, {eef_pos[2]:.4f}]")
                print(f"  target_pos: [{target_pos[0]:.4f}, {target_pos[1]:.4f}, {target_pos[2]:.4f}]")
                print(f"  handle_pos: [{handle_pos[0]:.4f}, {handle_pos[1]:.4f}, {handle_pos[2]:.4f}]")
                # check with relaxed threshold if gripper is closed
                if self.gripper_closed and self.grasp_wait > 15:
                    pos_reached_relaxed = pos_distance < self.POS_THRESHOLD_WAYPOINT2_GRASPED
                    print(f"  pos_reached_relaxed (gripped): {pos_reached_relaxed} (threshold: {self.POS_THRESHOLD_WAYPOINT2_GRASPED:.4f} m)")
                    print(f"  All conditions met (relaxed): {pos_reached_relaxed and self.gripper_closed and self.grasp_wait > 15}")
                else:
                    print(f"  All conditions met: {pos_reached and self.gripper_closed and self.grasp_wait > 15}")
            
            # use relaxed threshold if gripper is closed and we've waited enough
            if self.gripper_closed and self.grasp_wait > 15:
                pos_reached_for_transition = pos_distance < self.POS_THRESHOLD_WAYPOINT2_GRASPED
            else:
                pos_reached_for_transition = pos_reached
            
            if pos_reached_for_transition and self.gripper_closed and self.grasp_wait > 15:  # wait for gripper to close
                if self.segmented:
                    print(f"\n>>> TRANSITIONING FROM WAYPOINT 2 TO SEGMENTED HOLD (10) <<<")
                    self.waypoint = 10
                    self._post_grasp_hold = handle_pos.copy()
                    self._post_grasp_hold[2] -= self.GRIP_OFFSET_BELOW
                    self.pos_controller.reset(target=self._post_grasp_hold.copy())
                else:
                    # once gripped, switch to lifting vertically to 15cm above peg top
                    print(f"\n>>> TRANSITIONING FROM WAYPOINT 2 TO WAYPOINT 3 <<<")
                    print(f"  Final eef_pos: [{eef_pos[0]:.4f}, {eef_pos[1]:.4f}, {eef_pos[2]:.4f}]")
                    print(f"  Final handle_pos: [{handle_pos[0]:.4f}, {handle_pos[1]:.4f}, {handle_pos[2]:.4f}]")
                    self.waypoint = 3
                    # Store initial x,y position for waypoint 3 (keep fixed, only move z)
                    self.waypoint3_initial_pos = eef_pos[:3].copy()
                    # reset position controller: lift vertically to 15cm above peg top (keep x,y same)
                    peg_top_z = self.target_peg_pos[2]  # peg top is at z = 0.85
                    target_z = peg_top_z + 0.15  # 15cm above peg top
                    target_pos_lift = self.waypoint3_initial_pos.copy()  # use fixed x,y position
                    target_pos_lift[2] = target_z  # only change z
                    self.pos_controller.reset(target=target_pos_lift)
                    print(f"  Stored waypoint3_initial_pos: [{self.waypoint3_initial_pos[0]:.4f}, {self.waypoint3_initial_pos[1]:.4f}, {self.waypoint3_initial_pos[2]:.4f}]")
                    print(f"  Peg top z: {peg_top_z:.4f}, Target z (peg_top + 0.15): {target_z:.4f}")
                    print(f"  New target_pos_lift (vertical raise): [{target_pos_lift[0]:.4f}, {target_pos_lift[1]:.4f}, {target_pos_lift[2]:.4f}]")
                self._waypoint2_transition_debug = 0  # reset counter
        # advance from waypoint 3 to waypoint 4 when position is reached (lifted to 15cm above peg top)
        elif self.waypoint == 3:
            # debug output for waypoint 3 transition check
            if not hasattr(self, '_waypoint3_transition_debug'):
                self._waypoint3_transition_debug = 0
            self._waypoint3_transition_debug += 1
            if self._waypoint3_transition_debug % 10 == 0:  # print every 10 steps
                print(f"\n=== Waypoint 3 Transition Check (step {self._waypoint3_transition_debug}) ===")
                print(f"  pos_reached: {pos_reached} (distance: {pos_distance:.4f} m, threshold: {self.POS_THRESHOLD_WAYPOINT3:.4f} m)")
                print(f"  eef_pos: [{eef_pos[0]:.4f}, {eef_pos[1]:.4f}, {eef_pos[2]:.4f}]")
                print(f"  target_pos: [{target_pos[0]:.4f}, {target_pos[1]:.4f}, {target_pos[2]:.4f}]")
                print(f"  peg_top_z + 0.15: {self.target_peg_pos[2] + 0.15:.4f}")
            
            if pos_reached:
                # once lifted to 15cm above peg top, switch to horizontal rotation alignment
                print(f"\n>>> TRANSITIONING FROM WAYPOINT 3 TO WAYPOINT 4 <<<")
                print(f"  Final eef_pos: [{eef_pos[0]:.4f}, {eef_pos[1]:.4f}, {eef_pos[2]:.4f}]")
                self.waypoint3_final_pos = eef_pos[:3].copy()  # store position for waypoint 4
                
                self.waypoint = 4
                # Reset rotation controller for clean start
                self.rot_controller.reset(target=np.array([0.0]))
                # Clear any previous yaw error tracking
                if hasattr(self, '_last_yaw_error'):
                    del self._last_yaw_error
                print(f"  Stored waypoint3_final_pos: [{self.waypoint3_final_pos[0]:.4f}, {self.waypoint3_final_pos[1]:.4f}, {self.waypoint3_final_pos[2]:.4f}]")
                print(f"  Starting horizontal rotation (yaw only) to align gripper to home orientation")
                self._waypoint3_transition_debug = 0  # reset counter
        # advance from waypoint 4 to waypoint 5 when rotation is aligned
        elif self.waypoint == 4:
            # debug output for waypoint 4 transition check
            if not hasattr(self, '_waypoint4_transition_debug'):
                self._waypoint4_transition_debug = 0
            self._waypoint4_transition_debug += 1
            if self._waypoint4_transition_debug % 50 == 0:  # print every 50 steps
                waypoint4_threshold = 0.08  # same threshold as in rotation control
                print(f"\n=== Waypoint 4 Transition Check (step {self._waypoint4_transition_debug}) ===")
                print(f"  rot_aligned: {rot_aligned} (yaw_error: {yaw_error:.4f} rad, threshold: {waypoint4_threshold:.4f} rad = {np.degrees(waypoint4_threshold):.2f} deg)")
            
            if rot_aligned:
                # once rotation is aligned, switch to moving nut center above peg center
                print(f"\n>>> TRANSITIONING FROM WAYPOINT 4 TO WAYPOINT 5 <<<")
                print(f"  Final eef_pos: [{eef_pos[0]:.4f}, {eef_pos[1]:.4f}, {eef_pos[2]:.4f}]")
                print(f"  Final yaw_error: {yaw_error:.4f} rad ({np.degrees(yaw_error):.2f} deg)")
                
                # Calculate offset from nut center to end-effector (handle offset)
                # This offset will be used to position end-effector such that nut center is above peg
                nut_to_eef_offset = eef_pos[:3] - nut_pos[:3]
                self.waypoint5_nut_to_eef_offset = nut_to_eef_offset.copy()
                
                self.waypoint = 5
                # Calculate target end-effector position: peg x, y + offset
                # Calculate target z to ensure nut is high enough above peg (nut hangs below gripper)
                peg_top_z = self.target_peg_pos[2]  # peg top is at z = 0.85
                min_nut_z = peg_top_z + 0.15  # nut should be at least 15cm above peg top
                target_z_move = min_nut_z + nut_to_eef_offset[2]  # ensure nut is high enough
                # Also ensure we're at least as high as waypoint 3 (safety check)
                target_z_move = max(target_z_move, self.waypoint3_final_pos[2])
                
                # Add leftward offset (negative y direction), forward offset (positive x direction), and right offset (positive y direction) before releasing
                # This ensures nut center (eef_pos - offset) is slightly to the left and forward of peg x, y, with right offset
                target_pos_move = np.array([
                    self.target_peg_pos[0] + nut_to_eef_offset[0] + self.WAYPOINT5_FORWARD_OFFSET,  # peg x + offset + forward offset
                    self.target_peg_pos[1] + nut_to_eef_offset[1] - self.WAYPOINT5_LEFT_OFFSET + self.WAYPOINT5_RIGHT_OFFSET,  # peg y + offset - left offset + right offset
                    target_z_move  # ensure nut is high enough above peg top
                ])
                self.pos_controller.reset(target=target_pos_move)
                print(f"  Nut pos: [{nut_pos[0]:.4f}, {nut_pos[1]:.4f}, {nut_pos[2]:.4f}]")
                print(f"  Nut to eef offset: [{nut_to_eef_offset[0]:.4f}, {nut_to_eef_offset[1]:.4f}, {nut_to_eef_offset[2]:.4f}]")
                print(f"  Target peg pos: [{self.target_peg_pos[0]:.4f}, {self.target_peg_pos[1]:.4f}, {self.target_peg_pos[2]:.4f}]")
                print(f"  Left offset: {self.WAYPOINT5_LEFT_OFFSET:.4f} m ({self.WAYPOINT5_LEFT_OFFSET*100:.2f} cm)")
                print(f"  Forward offset: {self.WAYPOINT5_FORWARD_OFFSET:.4f} m ({self.WAYPOINT5_FORWARD_OFFSET*100:.2f} cm)")
                print(f"  Right offset: {self.WAYPOINT5_RIGHT_OFFSET:.4f} m ({self.WAYPOINT5_RIGHT_OFFSET*100:.2f} cm)")
                print(f"  Target eef pos (peg x,y + offset + offsets, waypoint3 z): [{target_pos_move[0]:.4f}, {target_pos_move[1]:.4f}, {target_pos_move[2]:.4f}]")
                print(f"  (This will position nut center slightly to the left and forward of peg x,y, with right offset)")
                print(f"  Starting movement to position nut center above peg center (with left, forward, and right offsets)")
                self._waypoint4_transition_debug = 0  # reset counter
        # advance from waypoint 5 to waypoint 6 when position is reached
        elif self.waypoint == 5:
            # debug output for waypoint 5 transition check
            if not hasattr(self, '_waypoint5_transition_debug'):
                self._waypoint5_transition_debug = 0
            self._waypoint5_transition_debug += 1
            if self._waypoint5_transition_debug % 50 == 0:  # print every 50 steps
                print(f"\n=== Waypoint 5 Transition Check (step {self._waypoint5_transition_debug}) ===")
                print(f"  pos_reached: {pos_reached} (distance: {pos_distance:.4f} m, threshold: {self.POS_THRESHOLD_WAYPOINT5:.4f} m = {self.POS_THRESHOLD_WAYPOINT5*100:.2f} cm)")
                print(f"  eef_pos: [{eef_pos[0]:.4f}, {eef_pos[1]:.4f}, {eef_pos[2]:.4f}]")
                print(f"  target_pos: [{target_pos[0]:.4f}, {target_pos[1]:.4f}, {target_pos[2]:.4f}]")
            
            if pos_reached:
                print(f"  Final eef_pos: [{eef_pos[0]:.4f}, {eef_pos[1]:.4f}, {eef_pos[2]:.4f}]")
                self.waypoint5_final_pos = eef_pos[:3].copy()  # store position for waypoint 6
                if self.segmented:
                    print(f"\n>>> TRANSITIONING FROM WAYPOINT 5 TO SEGMENTED HOLD (11) <<<")
                    self._hover_hold_target = target_pos.copy()
                    self.waypoint = 11
                    self.pos_controller.reset(target=self._hover_hold_target.copy())
                else:
                    # once positioned above peg center, switch to releasing gripper
                    print(f"\n>>> TRANSITIONING FROM WAYPOINT 5 TO WAYPOINT 6 <<<")
                    self.waypoint = 6
                    print(f"  Stored waypoint5_final_pos: [{self.waypoint5_final_pos[0]:.4f}, {self.waypoint5_final_pos[1]:.4f}, {self.waypoint5_final_pos[2]:.4f}]")
                    print(f"  Opening gripper to release nut")
                self._waypoint5_transition_debug = 0  # reset counter

        # debug output
        if not hasattr(self, '_last_waypoint'):
            self._last_waypoint = -1
        if self.waypoint != self._last_waypoint:
            print(f"Waypoint changed: {self._last_waypoint} -> {self.waypoint}")
            print(f"  pos_reached: {pos_reached}, rot_aligned: {rot_aligned}")
            print(f"  target_pos: {target_pos}")
            if self.waypoint <= 3:
                print(f"  handle_pos: {handle_pos}")
            if self.waypoint == 3 or self.waypoint == 4 or self.waypoint == 5 or self.waypoint == 6:
                print(f"  target_peg_pos: {self.target_peg_pos}")
                print(f"  nut_type: {self.nut_type}")
            print(f"  eef_pos: {eef_pos[:3]}")
            self._last_waypoint = self.waypoint
        
        # debug output for waypoint 1 movement
        if self.waypoint == 1:
            if not hasattr(self, '_waypoint1_debug_counter'):
                self._waypoint1_debug_counter = 0
            self._waypoint1_debug_counter += 1
            # print every 50 steps or when close to target
            if self._waypoint1_debug_counter % 50 == 0 or pos_distance < 0.1:
                print(f"\n=== Waypoint 1 Debug (step {self._waypoint1_debug_counter}) ===")
                print(f"  eef_pos: [{eef_pos[0]:.4f}, {eef_pos[1]:.4f}, {eef_pos[2]:.4f}]")
                print(f"  target_pos (handle + 5cm above): [{target_pos[0]:.4f}, {target_pos[1]:.4f}, {target_pos[2]:.4f}]")
                print(f"  handle_pos: [{handle_pos[0]:.4f}, {handle_pos[1]:.4f}, {handle_pos[2]:.4f}]")
                print(f"  nut_pos: [{nut_pos[0]:.4f}, {nut_pos[1]:.4f}, {nut_pos[2]:.4f}]")
                print(f"  pos_distance: {pos_distance:.4f} m ({pos_distance*100:.2f} cm)")
                print(f"  pos_reached: {pos_reached}")
                print(f"  controller_target: {self.pos_controller.target}")
                print(f"  action[:3]: {action[:3]}")
        
        # debug output for waypoint 2 movement (grasping)
        if self.waypoint == 2:
            if not hasattr(self, '_waypoint2_debug_counter'):
                self._waypoint2_debug_counter = 0
            self._waypoint2_debug_counter += 1
            # print every 50 steps or when close to target
            if self._waypoint2_debug_counter % 50 == 0 or pos_distance < 0.05:
                horizontal_distance = np.linalg.norm(eef_pos[:2] - handle_pos[:2])
                vertical_distance = abs(eef_pos[2] - (handle_pos[2] - self.GRIP_OFFSET_BELOW))
                print(f"\n=== Waypoint 2 Debug (step {self._waypoint2_debug_counter}) ===")
                print(f"  eef_pos: [{eef_pos[0]:.4f}, {eef_pos[1]:.4f}, {eef_pos[2]:.4f}]")
                print(f"  target_pos (handle - {self.GRIP_OFFSET_BELOW*100:.1f}cm): [{target_pos[0]:.4f}, {target_pos[1]:.4f}, {target_pos[2]:.4f}]")
                print(f"  handle_pos: [{handle_pos[0]:.4f}, {handle_pos[1]:.4f}, {handle_pos[2]:.4f}]")
                print(f"  pos_distance: {pos_distance:.4f} m ({pos_distance*100:.2f} cm)")
                print(f"  horizontal_distance: {horizontal_distance:.4f} m ({horizontal_distance*100:.2f} cm)")
                print(f"  vertical_distance: {vertical_distance:.4f} m ({vertical_distance*100:.2f} cm)")
                print(f"  pos_reached: {pos_reached}")
                print(f"  gripper_closed: {self.gripper_closed}")
                print(f"  grasp_wait: {self.grasp_wait}")
                print(f"  action[6] (gripper): {action[6]}")
                print(f"  action[:3]: {action[:3]}")
        
        # debug output for waypoint 3 movement (lifting)
        if self.waypoint == 3:
            if not hasattr(self, '_waypoint3_debug_counter'):
                self._waypoint3_debug_counter = 0
            self._waypoint3_debug_counter += 1
            # print every 50 steps or when close to target
            if self._waypoint3_debug_counter % 50 == 0 or pos_distance < 0.1:
                peg_top_z = self.target_peg_pos[2]
                target_z = peg_top_z + 0.15
                print(f"\n=== Waypoint 3 Debug (Vertical Lift, step {self._waypoint3_debug_counter}) ===")
                print(f"  eef_pos: [{eef_pos[0]:.4f}, {eef_pos[1]:.4f}, {eef_pos[2]:.4f}]")
                print(f"  target_pos (vertical raise to {target_z:.4f}m = peg_top {peg_top_z:.4f}m + 0.15m): [{target_pos[0]:.4f}, {target_pos[1]:.4f}, {target_pos[2]:.4f}]")
                print(f"  pos_distance: {pos_distance:.4f} m ({pos_distance*100:.2f} cm)")
                print(f"  pos_reached: {pos_reached}")
                print(f"  gripper_closed: {self.gripper_closed}")
                print(f"  action[6] (gripper): {action[6]}")
                print(f"  action[:3] (vertical movement): {action[:3]}")
        
        # debug output for waypoint 4 (restore home orientation)
        if self.waypoint == 4:
            if not hasattr(self, '_waypoint4_debug_counter'):
                self._waypoint4_debug_counter = 0
            self._waypoint4_debug_counter += 1
            # Calculate rotation error for display (using same method as rotation control)
            eef_quat = obs["robot0_eef_quat_site"]
            
            # Extract yaw using same method as control code
            _, _, home_yaw = T.mat2euler(T.quat2mat(self.home_q))
            _, _, eef_yaw = T.mat2euler(T.quat2mat(eef_quat))
            yaw_error = (home_yaw - eef_yaw + np.pi) % (2 * np.pi) - np.pi
            
            waypoint4_rot_threshold = 0.08  # same as in rotation control (tighter for proper alignment)
            
            # print every 50 steps or when close to alignment
            if self._waypoint4_debug_counter % 50 == 0 or abs(yaw_error) < 0.2:
                print(f"\n=== Waypoint 4 Debug (Restore Home Orientation - Yaw Only, step {self._waypoint4_debug_counter}) ===")
                print(f"  ROTATION ALIGNMENT (yaw only, position fixed):")
                print(f"    eef_quat (current): [{eef_quat[0]:.4f}, {eef_quat[1]:.4f}, {eef_quat[2]:.4f}, {eef_quat[3]:.4f}]")
                print(f"    home_q (target): [{self.home_q[0]:.4f}, {self.home_q[1]:.4f}, {self.home_q[2]:.4f}, {self.home_q[3]:.4f}]")
                print(f"    home_yaw: {home_yaw:.4f} rad ({np.degrees(home_yaw):.2f} deg)")
                print(f"    eef_yaw: {eef_yaw:.4f} rad ({np.degrees(eef_yaw):.2f} deg)")
                print(f"    yaw_error (wrapped): {yaw_error:.4f} rad ({np.degrees(yaw_error):.2f} deg)")
                print(f"    rot_aligned: {rot_aligned} (threshold: {waypoint4_rot_threshold:.4f} rad = {np.degrees(waypoint4_rot_threshold):.2f} deg)")
                print(f"  END-EFFECTOR (position fixed from waypoint 3):")
                print(f"    eef_pos: [{eef_pos[0]:.4f}, {eef_pos[1]:.4f}, {eef_pos[2]:.4f}]")
                print(f"    waypoint3_final_pos (target): [{target_pos[0]:.4f}, {target_pos[1]:.4f}, {target_pos[2]:.4f}]")
                print(f"    action[:3] (should be zeros): {action[:3]}")
                print(f"    action[3:6] (rotation - yaw only): {action[3:6]}")
        
        # debug output for waypoint 5 (move nut center above peg center)
        if self.waypoint == 5:
            if not hasattr(self, '_waypoint5_debug_counter'):
                self._waypoint5_debug_counter = 0
            self._waypoint5_debug_counter += 1
            # print every 50 steps or when close to target
            if self._waypoint5_debug_counter % 50 == 0 or pos_distance < 0.1:
                # Get nut position for reference
                nut_pos = obs.get(nut_pos_key, np.array([0.2, 0.1, 0.8]))
                print(f"\n=== Waypoint 5 Debug (Move Nut Center Above Peg Center, step {self._waypoint5_debug_counter}) ===")
                print(f"  POSITION ALIGNMENT:")
                print(f"    eef_pos: [{eef_pos[0]:.4f}, {eef_pos[1]:.4f}, {eef_pos[2]:.4f}]")
                print(f"    target_eef_pos (peg x,y + offset, waypoint3 z): [{target_pos[0]:.4f}, {target_pos[1]:.4f}, {target_pos[2]:.4f}]")
                print(f"    peg_center: [{self.target_peg_pos[0]:.4f}, {self.target_peg_pos[1]:.4f}, {self.target_peg_pos[2]:.4f}]")
                print(f"    nut_pos (current): [{nut_pos[0]:.4f}, {nut_pos[1]:.4f}, {nut_pos[2]:.4f}]")
                # Calculate horizontal distance from nut center to peg center (what we're actually trying to minimize)
                nut_to_peg_horizontal_dist = np.linalg.norm(nut_pos[:2] - self.target_peg_pos[:2])
                print(f"    nut_to_peg_horizontal_distance: {nut_to_peg_horizontal_dist:.4f} m ({nut_to_peg_horizontal_dist*100:.2f} cm)")
                if hasattr(self, 'waypoint5_nut_to_eef_offset'):
                    print(f"    nut_to_eef_offset: [{self.waypoint5_nut_to_eef_offset[0]:.4f}, {self.waypoint5_nut_to_eef_offset[1]:.4f}, {self.waypoint5_nut_to_eef_offset[2]:.4f}]")
                print(f"    eef_to_target_distance: {pos_distance:.4f} m ({pos_distance*100:.2f} cm)")
                print(f"    pos_reached: {pos_reached} (threshold: {self.POS_THRESHOLD_WAYPOINT5:.4f} m = {self.POS_THRESHOLD_WAYPOINT5*100:.2f} cm)")
                print(f"    action[:3] (position movement): {action[:3]}")
                print(f"    action[3:6] (rotation - should be zeros): {action[3:6]}")
        
        # debug output for waypoint 6 (release gripper)
        if self.waypoint == 6:
            if not hasattr(self, '_waypoint6_debug_counter'):
                self._waypoint6_debug_counter = 0
            self._waypoint6_debug_counter += 1
            # print every 50 steps
            if self._waypoint6_debug_counter % 50 == 0:
                # Get nut position for reference
                nut_pos = obs.get(nut_pos_key, np.array([0.2, 0.1, 0.8]))
                print(f"\n=== Waypoint 6 Debug (Release Gripper, step {self._waypoint6_debug_counter}) ===")
                print(f"  GRIPPER RELEASE:")
                print(f"    eef_pos: [{eef_pos[0]:.4f}, {eef_pos[1]:.4f}, {eef_pos[2]:.4f}]")
                print(f"    waypoint5_final_pos (target - position fixed): [{target_pos[0]:.4f}, {target_pos[1]:.4f}, {target_pos[2]:.4f}]")
                print(f"    peg_center: [{self.target_peg_pos[0]:.4f}, {self.target_peg_pos[1]:.4f}, {self.target_peg_pos[2]:.4f}]")
                print(f"    nut_pos: [{nut_pos[0]:.4f}, {nut_pos[1]:.4f}, {nut_pos[2]:.4f}]")
                print(f"    action[:3] (should be zeros - position fixed): {action[:3]}")
                print(f"    action[3:6] (rotation - should be zeros): {action[3:6]}")
                print(f"    action[6] (gripper - should be -1.0 to open): {action[6]}")
        
        # After waypoint 6 (gripper release), immediately switch to round nut
        if self.waypoint == 6 and self.current_nut == "Square":
            # Wait a brief moment after opening gripper to ensure it's fully open
            if not hasattr(self, '_waypoint6_release_wait'):
                self._waypoint6_release_wait = 0
            self._waypoint6_release_wait += 1
            
            # Wait ~0.25 seconds (5 steps at 0.05s dt) after opening gripper, then immediately switch (reduced for faster execution)
            if self._waypoint6_release_wait > 5:
                # Immediately switch to round nut after releasing square nut
                self.switch_to_round_nut(obs)
                self._waypoint6_release_wait = 0  # reset counter
                # After switching, we need to recalculate nut_pos and handle_pos for round nut
                # This will happen on next iteration since waypoint is now 0
        
        return action

        # # Target position: handle position, slightly above (5cm) for approach
        # target_pos = handle_pos.copy()
        # target_pos[2] += 0.05  # 5cm above handle
        
        # # Position control: move to handle position
        # self.pos_controller.reset(target=target_pos)
        # pos_control = self.pos_controller.update(eef_pos[:3], self.dt)
        # pos_control = np.clip(pos_control, -0.1, 0.1)
        # action[:3] = pos_control
        
        # # Rotation control: align gripper with handle
        # # Use relative quaternion to get yaw alignment
        # nut_to_eef_quat_key = f"{self.nut_type}Nut_to_robot0_eef_quat"
        # if nut_to_eef_quat_key in obs and np.sum(obs[nut_to_eef_quat_key]) != 0:
        #     # Extract yaw from relative quaternion (nut to end-effector)
        #     nut_to_eef_quat = obs[nut_to_eef_quat_key]
            
        #     # Handle quaternion format: scipy expects [x, y, z, w], robosuite might use [w, x, y, z]
        #     # Try direct format first (as user's code does)
        #     try:
        #         current_yaw = R.from_quat(nut_to_eef_quat).as_euler('xyz')[2]
        #     except:
        #         # If that fails, convert from [w, x, y, z] to [x, y, z, w]
        #         quat_converted = np.array([nut_to_eef_quat[1], nut_to_eef_quat[2], nut_to_eef_quat[3], nut_to_eef_quat[0]])
        #         current_yaw = R.from_quat(quat_converted).as_euler('xyz')[2]
            
        #     # Apply yaw rotation control with reduced gain and clipping to prevent shivering
        #     yaw_control = 0.1 * current_yaw  # Reduced gain from 0.2 to 0.1
        #     yaw_control = np.clip(yaw_control, -0.05, 0.05)  # Tighter clipping to prevent shivering
        #     action[5] = yaw_control
        # else:
        #     # No rotation control if quaternion not available
        #     action[5] = 0.0
        
        # # No roll or pitch control
        # action[3] = 0.0  # roll
        # action[4] = 0.0  # pitch
        
        # # Keep gripper open
        # action[6] = -1.0
        
        # return action

class DoorPolicy(object):
    """
    Policy for the Door Opening task.
    Goal: Rotate gripper 90 degrees first to be parallel to door, then grasp the door handle.
    Phase 0: Rotate gripper 90 degrees (pitch) to orient parallel to door (fingers vertical).
    Phase 1: Hover above handle (10cm above).
    Phase 2: Approach handle (3cm above).
    Phase 3: Grasp handle (gripper will grab top and bottom of handle).
    """
    def __init__(self, obs):
        """
        Args:
            obs (dict): Includes 'handle_pos'.
        """
        # get current end-effector position
        eef_pos = obs["robot0_eef_pos"]
        
        # initialize PID controller for position control
        self.pos_controller = PID(kp=10.0, ki=0.1, kd=5.0, target=eef_pos[:3])
        
        self.dt = 0.05
        self.waypoint = 0  # track which waypoint we're at
        # waypoints: 0 = rotate gripper 90 degrees, 1 = hover above handle, 2 = approach handle, 3 = grasp handle
        
        # thresholds for waypoint checking
        self.POS_THRESHOLD = 0.03  # 3cm for waypoints 1, 2
        self.POS_THRESHOLD_GRASP = 0.02  # 2cm for grasping
        
        # rotation parameters for initial gripper rotation (waypoint 0)
        self.initial_rotation_steps = 40  # number of steps to apply initial rotation
        self.initial_rotation_count = 0  # counter for rotation steps
        self.initial_rotation_angle = np.pi / 2  # 90 degrees pitch rotation to make gripper parallel to door
        # Apply rotation incrementally: divide total angle by number of steps
        # Rotate around y-axis (pitch) to orient gripper parallel to door (fingers vertical)
        self.initial_pitch_angle_per_step = self.initial_rotation_angle / self.initial_rotation_steps
        
        # track gripper state
        self.grasp_wait = 0
        self.gripper_closed = False
        
        # debug counter
        self.debug_counter = 0
        
        # timer for moving right after 35 seconds
        self.pull_right_steps = 2000  # tweaking this to find best time to move right
        self.pull_right_distance = 0.15  # 15cm to the right
        self.pull_start_pos = None  # will store position when pull starts
        
        # store initial handle position for reference
        # Note: robosuite uses 'handle_pos' not 'door_handle_pos'
        if "handle_pos" in obs:
            self.initial_handle_pos = obs["handle_pos"].copy()
        else:
            self.initial_handle_pos = None
        
        print(f"\n=== DoorPolicy Initialized ===")
        print(f"  Initial eef_pos: [{eef_pos[0]:.4f}, {eef_pos[1]:.4f}, {eef_pos[2]:.4f}]")
        if self.initial_handle_pos is not None:
            print(f"  Initial handle_pos: [{self.initial_handle_pos[0]:.4f}, {self.initial_handle_pos[1]:.4f}, {self.initial_handle_pos[2]:.4f}]")
        print(f"  Starting waypoint: {self.waypoint}")
        
    def get_action(self, obs):
        """
        Returns:
            np.ndarray: 7D action (Delta-X, Delta-Y, Delta-Z, Axis-Angle [3], Gripper).
        """
        try:
            action = np.zeros(7)
            
            # debug: print available observation keys on first call
            if not hasattr(self, '_obs_keys_printed'):
                print(f"\n=== Available observation keys ===")
                print(f"  Keys: {list(obs.keys())}")
                self._obs_keys_printed = True
            
            # get current end-effector position
            if "robot0_eef_pos" not in obs:
                print(f"ERROR: robot0_eef_pos not in observations!")
                return action
            
            eef_pos = obs["robot0_eef_pos"]
            
            # get door handle position
            # Note: robosuite uses 'handle_pos' not 'door_handle_pos'
            if "handle_pos" not in obs:
                if not hasattr(self, '_handle_warning_printed'):
                    print(f"WARNING: handle_pos not in observations!")
                    print(f"  Available keys: {list(obs.keys())}")
                    self._handle_warning_printed = True
                # fallback: just hold position if handle not available
                target_pos = eef_pos[:3].copy()
                self.pos_controller.reset(target=target_pos)
                control = self.pos_controller.update(eef_pos[:3], self.dt)
                action[:3] = np.clip(control, -0.1, 0.1)
                action[-1] = -1.0  # keep gripper open
                return action
            
            handle_pos = obs["handle_pos"]
            
            # update initial handle position if not set
            if self.initial_handle_pos is None:
                self.initial_handle_pos = handle_pos.copy()
                print(f"  Set initial handle position: [{self.initial_handle_pos[0]:.4f}, {self.initial_handle_pos[1]:.4f}, {self.initial_handle_pos[2]:.4f}]")
            
            # debug output (print every 50 steps or when waypoint changes)
            self.debug_counter += 1
            if not hasattr(self, '_last_waypoint'):
                self._last_waypoint = -1
            
            waypoint_changed = (self.waypoint != self._last_waypoint)
            should_debug = waypoint_changed or (self.debug_counter % 50 == 0)
            
            if should_debug:
                print(f"\n=== DoorPolicy Debug (step {self.debug_counter}, waypoint {self.waypoint}) ===")
                print(f"  eef_pos: [{eef_pos[0]:.4f}, {eef_pos[1]:.4f}, {eef_pos[2]:.4f}]")
                print(f"  handle_pos: [{handle_pos[0]:.4f}, {handle_pos[1]:.4f}, {handle_pos[2]:.4f}]")
                if waypoint_changed:
                    print(f"  >>> WAYPOINT CHANGED: {self._last_waypoint} -> {self.waypoint} <<<")
            
            # determine target position and gripper state based on waypoint
            target_pos = None
            target_gripper = -1.0  # default: gripper open
            
            if self.waypoint == 0:
                # waypoint 0: rotate gripper 90 degrees (roll) before approaching
                # Hold position while rotating
                if not hasattr(self, 'initial_rotation_start_pos'):
                    self.initial_rotation_start_pos = eef_pos[:3].copy()
                target_pos = self.initial_rotation_start_pos.copy()
                
            elif self.waypoint == 1:
                # waypoint 1: hover above handle (10cm above)
                target_pos = handle_pos.copy()
                target_pos[2] += 0.10  # 10cm above handle
                
            elif self.waypoint == 2:
                # waypoint 2: approach handle (3cm above)
                target_pos = handle_pos.copy()
                target_pos[2] += 0.03  # 3cm above handle
                
            elif self.waypoint == 3:
                # waypoint 3: grasp handle (at handle position)
                target_gripper = 1.0  # keep gripper closed (or will close it)
                
                # close gripper when close to handle
                distance_to_handle = np.linalg.norm(eef_pos[:3] - handle_pos)
                horizontal_dist = np.linalg.norm(eef_pos[:2] - handle_pos[:2])
                vertical_dist = abs(eef_pos[2] - handle_pos[2])
                
                # require horizontal alignment and close distance
                if (horizontal_dist < 0.015 and vertical_dist < 0.02) or self.gripper_closed:
                    self.gripper_closed = True
                    self.grasp_wait += 1
                    
                    # Store the position when we first close the gripper
                    if not hasattr(self, 'grasp_position'):
                        self.grasp_position = eef_pos[:3].copy()
                        print(f"  >>> GRASPED HANDLE - Stored grasp position: [{self.grasp_position[0]:.4f}, {self.grasp_position[1]:.4f}, {self.grasp_position[2]:.4f}] <<<")
                else:
                    # Not close enough yet - keep gripper open
                    target_gripper = -1.0
                
                # After 35 seconds, move gripper 15cm to the right
                if self.debug_counter >= self.pull_right_steps:
                    # Store pull start position on first step of pull
                    if self.pull_start_pos is None:
                        self.pull_start_pos = eef_pos[:3].copy()
                        print(f"  >>> 35 SECONDS ELAPSED - Starting pull to the right <<<")
                        print(f"  >>> Pull start position: [{self.pull_start_pos[0]:.4f}, {self.pull_start_pos[1]:.4f}, {self.pull_start_pos[2]:.4f}] <<<")
                        print(f"  >>> Pulling {self.pull_right_distance*100:.2f} cm to the right (positive Y) <<<")
                    
                    # Target position is pull start position + 15cm to the right
                    target_pos = self.pull_start_pos.copy()
                    target_pos[1] += self.pull_right_distance  # move right (positive Y)
                else:
                    # Before 35 seconds, target handle position
                    target_pos = handle_pos.copy()
            
            if target_pos is None:
                target_pos = eef_pos[:3].copy()
            
            # position control
            pos_control_raw = None
            pos_control = None
            
            if self.waypoint == 0:
                # Waypoint 0: Hold position while rotating gripper
                target_diff = np.linalg.norm(self.pos_controller.target - target_pos)
                if target_diff > 0.001:
                    self.pos_controller.reset(target=target_pos)
                pos_control_raw = self.pos_controller.update(eef_pos[:3], self.dt)
                pos_control = np.clip(pos_control_raw, -0.1, 0.1)
                action[:3] = pos_control
            else:
                # For waypoints 1, 2, 3: normal position control
                # reset controller if target changed significantly
                target_diff = np.linalg.norm(self.pos_controller.target - target_pos)
                if target_diff > 0.001:  # if target changed by more than 1mm, reset
                    self.pos_controller.reset(target=target_pos)
                
                pos_control_raw = self.pos_controller.update(eef_pos[:3], self.dt)
                pos_control = np.clip(pos_control_raw, -0.1, 0.1)
                action[:3] = pos_control
            
            # rotation control
            if self.waypoint == 0:
                # Waypoint 0: Rotate gripper 90 degrees (pitch) to make it parallel to door
                # This orients gripper so fingers are vertical, allowing it to grab top/bottom of handle
                if self.initial_rotation_count < self.initial_rotation_steps:
                    # Apply incremental pitch rotation around y-axis
                    action[3] = 0.0  # no roll
                    action[4] = self.initial_pitch_angle_per_step  # incremental pitch rotation (around y-axis)
                    action[5] = 0.0  # no yaw
                    self.initial_rotation_count += 1
                else:
                    # Stop rotation after completing the steps
                    action[3:6] = np.zeros(3)
            else:
                # no rotation control for other waypoints (keep current orientation)
                action[3:6] = np.zeros(3)
            
            # set gripper
            action[6] = target_gripper
            
            # debug output for control signals
            if should_debug:
                print(f"  target_pos: [{target_pos[0]:.4f}, {target_pos[1]:.4f}, {target_pos[2]:.4f}]")
                if self.waypoint != 3:
                    print(f"  controller.target: [{self.pos_controller.target[0]:.4f}, {self.pos_controller.target[1]:.4f}, {self.pos_controller.target[2]:.4f}]")
                    if pos_control_raw is not None:
                        print(f"  pos_control (before clip): {pos_control_raw}")
                    if pos_control is not None:
                        print(f"  pos_control (after clip): {pos_control}")
                elif self.waypoint == 3 and self.pull_start_pos is not None:
                    # Show position control info when pulling
                    print(f"  controller.target: [{self.pos_controller.target[0]:.4f}, {self.pos_controller.target[1]:.4f}, {self.pos_controller.target[2]:.4f}]")
                    if pos_control_raw is not None:
                        print(f"  pos_control (before clip): {pos_control_raw}")
                    if pos_control is not None:
                        print(f"  pos_control (after clip): {pos_control}")
                print(f"  action[:3]: {action[:3]}")
                print(f"  action[6] (gripper): {action[6]}")
                if self.waypoint == 0:
                    print(f"  rotation_count: {self.initial_rotation_count} / {self.initial_rotation_steps}")
                    print(f"  action[4] (pitch per step, to orient gripper parallel to door): {action[4]:.4f} rad ({np.degrees(action[4]):.2f} deg)")
                    total_rotation_so_far = self.initial_rotation_count * self.initial_pitch_angle_per_step
                    print(f"  total rotation so far: {total_rotation_so_far:.4f} rad ({np.degrees(total_rotation_so_far):.2f} deg)")
                if self.waypoint == 3:
                    print(f"  gripper_closed: {self.gripper_closed}, grasp_wait: {self.grasp_wait}")
                    print(f"  step_count: {self.debug_counter} / {self.pull_right_steps} (35 seconds)")
                    if hasattr(self, 'grasp_position'):
                        print(f"  grasp_position: [{self.grasp_position[0]:.4f}, {self.grasp_position[1]:.4f}, {self.grasp_position[2]:.4f}]")
                    if self.pull_start_pos is not None:
                        print(f"  pull_start_pos: [{self.pull_start_pos[0]:.4f}, {self.pull_start_pos[1]:.4f}, {self.pull_start_pos[2]:.4f}]")
                        print(f"  target_pos (pull right): [{target_pos[0]:.4f}, {target_pos[1]:.4f}, {target_pos[2]:.4f}]")
            
            # check waypoint completion and advance
            pos_distance = np.linalg.norm(eef_pos[:3] - target_pos)
            
            # use different thresholds for different waypoints
            if self.waypoint == 0:
                # for initial rotation, check if we've completed the rotation steps
                waypoint_reached = self.initial_rotation_count >= self.initial_rotation_steps
            elif self.waypoint == 1 or self.waypoint == 2:
                waypoint_reached = pos_distance < self.POS_THRESHOLD
            elif self.waypoint == 3:
                # for grasping waypoint, require position close AND gripper closed for a bit
                waypoint_reached = (pos_distance < self.POS_THRESHOLD_GRASP) and (self.grasp_wait > 20)
            else:
                waypoint_reached = False
            
            # debug output for waypoint completion check
            if should_debug:
                print(f"  pos_distance: {pos_distance:.4f} m ({pos_distance*100:.2f} cm)")
                print(f"  waypoint_reached: {waypoint_reached}")
                if self.waypoint == 0:
                    print(f"  rotation_count: {self.initial_rotation_count} / {self.initial_rotation_steps}")
                    total_rotation_so_far = self.initial_rotation_count * self.initial_pitch_angle_per_step
                    print(f"  total rotation: {total_rotation_so_far:.4f} rad ({np.degrees(total_rotation_so_far):.2f} deg) / {self.initial_rotation_angle:.4f} rad ({np.degrees(self.initial_rotation_angle):.2f} deg)")
                elif self.waypoint == 1 or self.waypoint == 2:
                    print(f"  threshold: {self.POS_THRESHOLD:.4f} m ({self.POS_THRESHOLD*100:.2f} cm)")
                elif self.waypoint == 3:
                    print(f"  threshold: {self.POS_THRESHOLD_GRASP:.4f} m ({self.POS_THRESHOLD_GRASP*100:.2f} cm)")
                    print(f"  grasp_wait: {self.grasp_wait} (need > 20)")
            
            if waypoint_reached and self.waypoint < 3:
                old_waypoint = self.waypoint
                self.waypoint += 1
                self.grasp_wait = 0
                
                print(f"\n>>> ADVANCING WAYPOINT: {old_waypoint} -> {self.waypoint} <<<")
                print(f"  Final eef_pos: [{eef_pos[0]:.4f}, {eef_pos[1]:.4f}, {eef_pos[2]:.4f}]")
                print(f"  Final target_pos: [{target_pos[0]:.4f}, {target_pos[1]:.4f}, {target_pos[2]:.4f}]")
                
                # When advancing from waypoint 0 (rotation), print completion message
                if old_waypoint == 0:
                    print(f"  Completed initial gripper rotation (90 degrees pitch - gripper now parallel to door)")
                    print(f"  Gripper fingers are now vertical, ready to grab top/bottom of handle")
                    print(f"  Now proceeding to approach handle")
            
            # Once we reach waypoint 3 (grasping), stay there after grasping
            if self.waypoint == 3 and waypoint_reached:
                if should_debug:
                    print(f"  >>> COMPLETED GRASP - Staying at waypoint 3 <<<")
            
            # update last waypoint for change detection
            self._last_waypoint = self.waypoint
            
            return action
            
        except Exception as e:
            print(f"\nERROR in DoorPolicy.get_action: {e}")
            import traceback
            traceback.print_exc()
            # return safe action
            action = np.zeros(7)
            action[-1] = -1.0  # keep gripper open
            return action